- tiling-assistant@leleat-on-github/extension.js
- tiling-assistant@leleat-on-github/metadata.json
- tiling-assistant@leleat-on-github/src/extension/activeWindowHint.js
- tiling-assistant@leleat-on-github/src/extension/moveHandler.js
- tiling-assistant@leleat-on-github/src/extension/utility.js
GNOME removed grab op's manual handling support, but we can avoid them by just adapting the motion.
Tested in both wayland and X11, while I didn't test if older versions could still work using the same codepath (yet).
> GNOME 44 support

- tiling-assistant@leleat-on-github/src/extension/layoutsManager.js
While the popup was positioned to be at the center of the current monitor in absolute coords, it was a child of a widget that spanned only the workArea (and not the full monitors). So instead make the parent equal the Main.uiGroup and in turn the global.stage.
Fix https://github.com/Leleat/Tiling-Assistant/issues/241
> Layouts: Fix position of the search-a-layout popup on multi-monitor setups

- tiling-assistant@leleat-on-github/src/extension/moveHandler.js
- tiling-assistant@leleat-on-github/src/extension/resizeHandler.js
Mutter introduced a new flag META_GRAB_OP_WINDOW_FLAG_UNCONSTRAINED (1024). It is used to indicate wether a window is unconstrainted during a grab operation e. g. wether it can go under the top bar. As an example, this flag will be set, if you use super+mouse buttons. We currently only check for equality when looking at the Meta.GrabOp instead of using a bitwise or. That's why for simplicitiy's sake, just remove the new flag before working with the grabOp (and take the new flag into account during an upcoming larger refactor).
> Window Grab Operations: Fix regression for GNOME 44

- tiling-assistant@leleat-on-github/extension.js
- tiling-assistant@leleat-on-github/schemas/org.gnome.shell.extensions.tiling-assistant.gschema.xml
- tiling-assistant@leleat-on-github/src/common.js
This is the "hacky" version of #243 in a way that can be supported by current gnome.
---
The extension is overriding the user settings by writing on them, sadly this
implies various issues because even if we reset them on extension unloading,
a shell crash or mis-behavior could always lead to affect user settings.
Tiling assistant replaces the user settings when running, but not to loose the
user settings, we need to save them around so that when the extension gets
unloaded they can be restored.
So add a SettingsOverrider class that:
- Replaces the user settings with the extensions one
- Remembers what has been changed and saves it locally and in our settings
- When the extension is unloaded the settings are restored or reset
Now, in case gnome-shell is stopped or the extension has …
> extension: Add SettingsOverrider to preserve user settings

- tiling-assistant@leleat-on-github/extension.js
Fixes https://github.com/Leleat/Tiling-Assistant/issues/258
> Extension: Properly restore tiling props on all workspaces after unlocking the screen.

- tiling-assistant@leleat-on-github/src/extension/moveHandler.js
Fixes https://github.com/Leleat/Tiling-Assistant/issues/275, https://github.com/Leleat/Tiling-Assistant/issues/278
> moveHandler: Update tile group when the window changes monitor

- tiling-assistant@leleat-on-github/src/extension/tilingWindowManager.js
Fixes #289.
By moving the window to the tile's monitor before moving and resizing fixes the bug. I uploaded a video to show the result:
https://github.com/Leleat/Tiling-Assistant/assets/14203981/2c289578-4051-40cc-a024-659dd57ac889
Tested on:
- Distro (incl. version): Ubuntu 23.04
- GNOME Shell version: 44.3
- Extension version: version 42, and I am on main branch
- Wayland
> fix: ensure the window is moved to the tile's monitor before moving and resizing it

- scripts/aur-build/PKGBUILD
The edited PKGBUILD has been tested and packages the extension correctly as expected.
> Preserve some original changes of PKGBUILD

- scripts/aur-build/PKGBUILD
Closes https://github.com/Leleat/Tiling-Assistant/issues/296
> scripts: Update PKGBUILD to compile completely from source

- tiling-assistant@leleat-on-github/extension.js
- tiling-assistant@leleat-on-github/prefs.js
- tiling-assistant@leleat-on-github/schemas/org.gnome.shell.extensions.tiling-assistant.gschema.xml
- tiling-assistant@leleat-on-github/src/common.js
- tiling-assistant@leleat-on-github/src/extension/activeWindowHint.js
- tiling-assistant@leleat-on-github/src/extension/altTab.js
- tiling-assistant@leleat-on-github/src/extension/keybindingHandler.js
- tiling-assistant@leleat-on-github/src/extension/layoutsManager.js
- tiling-assistant@leleat-on-github/src/extension/moveHandler.js
- tiling-assistant@leleat-on-github/src/extension/resizeHandler.js
- tiling-assistant@leleat-on-github/src/extension/tileEditingMode.js
- tiling-assistant@leleat-on-github/src/extension/tilingWindowManager.js
- tiling-assistant@leleat-on-github/src/extension/utility.js
- tiling-assistant@leleat-on-github/src/prefs/layoutsPrefs.js
- tiling-assistant@leleat-on-github/src/ui/prefs.ui
some small changes/refactoring I had laying around. See commits.
> Small changes

- .github/workflows/run-ci.yml
- .stylelintrc.yml
Since we now have a package.json file just use `npm i` to install the linter(s). Also remove stylelint since it was pretty much unused cause T-A barely uses CSS.
> CI: Remove stylelint and use package.json to install deps

- .github/workflows/run-ci.yml
- scripts/update-tl.sh
- tiling-assistant@leleat-on-github/src/extension/keybindingHandler.js
- tiling-assistant@leleat-on-github/src/extension/layoutsManager.js
- tiling-assistant@leleat-on-github/src/extension/tileEditingMode.js
- tiling-assistant@leleat-on-github/src/prefs/layoutRowEntry.js
- tiling-assistant@leleat-on-github/src/ui/prefs.ui
I am not sure, if there are some conventions when it comes to translator comments or how detailed they should be... but at minimum the comments now provide the location of the untranslated text (not the code location but the location from a user's perspective).
> Misc: Add translation comments

- tiling-assistant@leleat-on-github/src/extension/moveHandler.js
> The default move mode is activated when no modifer key is pressed. That may be to restrictive however because the `Super` key is used when the user wants a window to span multiple tiles. So instead now fallback to the default move mode, only if used modifier keys aren't pressed.
>
> Fixes https://github.com/Leleat/Tiling-Assistant/issues/339
> MoveHandler: Ignore unused mods for determining the MoveModes

- tiling-assistant@leleat-on-github/extension.js
- tiling-assistant@leleat-on-github/src/prefs/layoutsPrefs.js
Those files existing is expected at all times after the initial creation.
As a result, journal continued being spammed with errors like:
Gio.IOErrorEnum: Error creating directory ~/.config/tiling-assistant: File exists
Gio.IOErrorEnum: Error opening file “~/.config/tiling-assistant/tiledSessionRestore.json”: File exists
The logging was only added in 50a1757d17e94bfe787d1f3aced2572fa26ae43a to appease ESLint,
so let’s add more specific `catch` body instead.
> Misc: Ignore error that file exists when creating it

- .github/ignore-words.txt
- tiling-assistant@leleat-on-github/src/extension/keybindingHandler.js
When maximizing a window vertically or horizontally, we've added gaps to the window like we normally do to tiled windows. This makes sense if the window is already tiled. If the window is floating, we shouldn't add gaps to it and instead should keep the currently visible size.
Fixes https://github.com/Leleat/Tiling-Assistant/issues/349
> keybindingHandler: maximize vertically/horizontally without gaps

- tiling-assistant@leleat-on-github/extension.js
- tiling-assistant@leleat-on-github/src/extension/resizeHandler.js
- tiling-assistant@leleat-on-github/src/extension/tilingWindowManager.js
While I don't know why if it's expected that my extension crashes GNOME Shell when trying to access some window props during a screen lock or if it's a bug in mutter... but either way. This should workaround the crash.
Fixes: https://github.com/Leleat/Tiling-Assistant/issues/267
> fix: save state on un/tiling instead of session lock/unlock

- tiling-assistant@leleat-on-github/metadata.json
From testing in a VM (Fedora Rawhide) with GNOME Shell 47.alpha, it appears the extension is working just fine. So just update metadata.json.
Also drop support for GNOME 45 and 46 from metadata.json since I plan to merge some MRs that are incompatible with (semantic) versioning for older releases. I will instead create branches for the older versions and cherry-pick bug fixes.
> feat: update metadata.json for GNOME 47

- translations/pl.po
Fixes https://github.com/Leleat/Tiling-Assistant/issues/370
> fix: fix metadata for Polish TL

- tiling-assistant@leleat-on-github/src/dependencies/unexported/altTab.js
- tiling-assistant@leleat-on-github/src/dependencies/unexported/switcherPopup.js
- tiling-assistant@leleat-on-github/src/extension/altTab.js
- tiling-assistant@leleat-on-github/src/extension/tilingPopup.js
I was lazy in the past and "extended" GNOME's app switcher so that I didn't need to write the tiling popup from scratch. Besides the fact that this was a bad usage, it also caused compatibility issues with other extensions that modify the app switcher or switcher popup like aatws.
As a quick fix, I've just pulled in the code from the app switcher and switcher popup from GNOME Shell into the extension. I only amended some import statements. It would be a nice idea to rewrite the tiling popup "properly".
fixes: https://github.com/Leleat/Tiling-Assistant/issues/381
> fix: improve compatibility with aatws

- tiling-assistant@leleat-on-github/src/extension/tilingWindowManager.js
This is only a workaround for the linked issue below. Currently, retiling a tiled window via the Tiling Popup may freeze the window (see the issue for more details on the STR). A better way to fix this would be to implement custom animations for tiling (instead of misusing GNOME's existing solution).
related: https://github.com/Leleat/Tiling-Assistant/issues/376
> Disable anims for tiled windows

- tiling-assistant@leleat-on-github/prefs.js
- tiling-assistant@leleat-on-github/schemas/org.gnome.shell.extensions.tiling-assistant.gschema.xml
- tiling-assistant@leleat-on-github/src/common.js
- tiling-assistant@leleat-on-github/src/extension/focusHint.js
- tiling-assistant@leleat-on-github/src/ui/prefs.ui
> Improve focus hint's compatibility with transparent windows

- CHANGELOG.md
- scripts/aur-build/.SRCINFO
- scripts/aur-build/PKGBUILD
- tiling-assistant@leleat-on-github/metadata.json
- translations/cs.po
- translations/de_CH.po
- translations/de_DE.po
- translations/es.po
- translations/hu.po
- translations/it_IT.po
- translations/ja.po
- translations/main.pot
- translations/nl.po
- translations/pl.po
- translations/pt_BR.po
- translations/ru.po
- translations/uk.po
- translations/zh_TW.po
Let's make a release with some fixes/additions for GNOME 47 before transitioning to GNOME 48
> Release 50

- tiling-assistant@leleat-on-github/src/extension/moveHandler.js
So far, we've ignored skip-taskbar windows when trying to tile them (in TilingWindowManager.tile). The reason is that those windows probably shouldn't be allowed to be tiled, as they are usually stuff like modal dialogs etc. But at the moment we do show the tile preview for those windows, which gives the impression that we allow them to be tiled.
I guess, we could allow skip-taskbar windows to be tiled (as long as they are resizable) but I think there may be more issues with them, e. g. when using modal dialogs that the parent window may be tiled but the dialog not. So I think it's better to just ignore them for now. attach-modal-dialogs settings is relevant to this issue.
Closes https://github.com/Leleat/Tiling-Assistant/issues/387
> ignore move op for unresizable and skip_taskbar windows

- ambient.d.ts
- jsconfig.json
- package-lock.json
- package.json
- tiling-assistant@leleat-on-github/prefs.js
- tiling-assistant@leleat-on-github/src/common.js
- tiling-assistant@leleat-on-github/src/extension/focusHint.js
- tiling-assistant@leleat-on-github/src/extension/moveHandler.js
- tiling-assistant@leleat-on-github/src/extension/tileEditingMode.js
- tiling-assistant@leleat-on-github/src/extension/tilingPopup.js
- tiling-assistant@leleat-on-github/src/extension/tilingWindowManager.js
- tiling-assistant@leleat-on-github/src/extension/utility.js
- tiling-assistant@leleat-on-github/src/prefs/layoutRowEntry.js
- tiling-assistant@leleat-on-github/src/prefs/layoutsPrefs.js
- tiling-assistant@leleat-on-github/src/prefs/shortcutListener.js
> Some minor ports of commits from #354

- tiling-assistant@leleat-on-github/src/extension/moveHandler.js
This partially reverts https://github.com/Leleat/Tiling-Assistant/commit/d960eed6bdf162000c15b1141fa9fb5cf5da283c. That commit added a check to ensure that
unresizable and skip_taskbar windows are ignored during drag and drop
operations to fix https://github.com/Leleat/Tiling-Assistant/issues/387, which was about the tile preview being shown
for windows that can't be tiled.
This doesn't work. "real" maximized windows don't allow resizing. So if
a window was maximized at the start of the DND operation we skipped the
whole tiling code. So let's only ignore skip_taskbar windows. This means
actually unresizable windows may trigger the tile preview (https://github.com/Leleat/Tiling-Assistant/issues/387), but
that is better than skipping the whole DND code for maximized windows,
which is more …
> fix: don't ignore unresizable windows during DND

- tiling-assistant@leleat-on-github/metadata.json
- tiling-assistant@leleat-on-github/src/extension/focusHint.js
- tiling-assistant@leleat-on-github/src/extension/keybindingHandler.js
- tiling-assistant@leleat-on-github/src/extension/moveHandler.js
- tiling-assistant@leleat-on-github/src/extension/tilingWindowManager.js
Mutter windows maximization API changed [1], and now it's not possible to perform partial maximizations, I feel that this is affecting the extension (let's discuss that upstream in case), but still we can have something working meanwhile by using the new API.
[1] https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/4415
> extension: Add initial compatbility for GNOME 49
