Leleat/Tiling-Assistant

tiling-assistant@leleat-on-github/extension.js
Implemented the feature as raised in #46.
As with the last patch, it's more of a working proof of concept, until your recode takes shape.
I've prefixed all named methods/variables 'monitorMove', so they will not be intermingled with the rest of the code. I'll be pulling another update to make the prior pull request follow this naming convention for consistency and to potentially aid in your recode.
=> Implemented monitor-switching grace period.

translations/zh_TW.po
It is still incomplete, I hope more Traditional Chinese users can help me to translate it properly.
=> Create zh_TW for Traditional Chinese users in Taiwan.

translations/ja.po
Thank you for the wonderful extension!
I translated some of it into Japanese.
=> add japanese translations

translations/de_CH.po
I have translated everything into German. Since I am from Switzerland, the spelling is `de_CH`. But for Germany you can actually Copy/Pate the file. There are only marginal differences.
Unfortunately I'm not 100% sure about all translations, because I don't understand all functions :-).
=> german (switzerland) translation added

translations/pt_BR.po
Added missing translations and improved existing ones based on context.
=> Update Brazillian Portuguese Translation

tiling-assistant@leleat-on-github/prefs.js, tiling-assistant@leleat-on-github/schemas/org.gnome.shell.extensions.tiling-assistant.gschema.xml, tiling-assistant@leleat-on-github/src/common.js, tiling-assistant@leleat-on-github/src/extension/resizeHandler.js, tiling-assistant@leleat-on-github/src/extension/tilingWindowManager.js, tiling-assistant@leleat-on-github/src/extension/utility.js, tiling-assistant@leleat-on-github/src/ui/prefs.ui
Figured that I'd open a PR for this. It seems to work fine for me, but I don't usually have tiling setups more complex than quarter tiling. This should close issue #146.
=> Implemented individual screen gaps

translations/nl.po
Not complete yet, but some more translated strings.
=> Update Dutch translation

translations/de_DE.po
First changes and extensions of translations in the German language and first participation in the project
=> Add further German translations

translations/de_DE.po
The second commit completes the previous work on the German translation. All open points have been translated.
=> Feat: Full German translation

scripts/build.sh, translations/ja.po
- removes a warning for the Japanese translation
- fixes the build; the locale directory in the extensions directory is removed before the generated locales are moved into it
=> Fixes for the local build.

.eslintrc.json, README.md, tiling-assistant@leleat-on-github/extension.js, tiling-assistant@leleat-on-github/metadata.json, tiling-assistant@leleat-on-github/prefs.js, tiling-assistant@leleat-on-github/src/common.js, tiling-assistant@leleat-on-github/src/dependencies/gi.js, tiling-assistant@leleat-on-github/src/dependencies/prefs.js, tiling-assistant@leleat-on-github/src/dependencies/prefs/gi.js, tiling-assistant@leleat-on-github/src/dependencies/shell.js, tiling-assistant@leleat-on-github/src/dependencies/unexported/altTab.js, tiling-assistant@leleat-on-github/src/dependencies/unexported/windowManager.js, tiling-assistant@leleat-on-github/src/extension/activeWindowHint.js, tiling-assistant@leleat-on-github/src/extension/altTab.js, tiling-assistant@leleat-on-github/src/extension/keybindingHandler.js, tiling-assistant@leleat-on-github/src/extension/layoutsManager.js, tiling-assistant@leleat-on-github/src/extension/moveHandler.js, tiling-assistant@leleat-on-github/src/extension/resizeHandler.js, tiling-assistant@leleat-on-github/src/extension/tileEditingMode.js, tiling-assistant@leleat-on-github/src/extension/tilingPopup.js, tiling-assistant@leleat-on-github/src/extension/tilingWindowManager.js, tiling-assistant@leleat-on-github/src/extension/utility.js, tiling-assistant@leleat-on-github/src/prefs/layoutRow.js, tiling-assistant@leleat-on-github/src/prefs/layoutRowEntry.js, tiling-assistant@leleat-on-github/src/prefs/layoutsPrefs.js, tiling-assistant@leleat-on-github/src/prefs/shortcutListener.js
(Updated)
~~Almost~~ everything should work now. ~~Known issue(s)~~:
=> Port to Gnome Shell 45

CHANGELOG.md, scripts/aur-build/.SRCINFO, scripts/aur-build/PKGBUILD, tiling-assistant@leleat-on-github/metadata.json, translations/cs.po, translations/de_CH.po, translations/de_DE.po, translations/es.po, translations/hu.po, translations/it_IT.po, translations/ja.po, translations/main.pot, translations/nl.po, translations/pt_BR.po, translations/zh_TW.po
=> Release: Bump version to 44

tiling-assistant@leleat-on-github/metadata.json, tiling-assistant@leleat-on-github/src/extension/altTab.js, tiling-assistant@leleat-on-github/src/extension/tileEditingMode.js, tiling-assistant@leleat-on-github/src/extension/tilingPopup.js, tiling-assistant@leleat-on-github/src/extension/tilingWindowManager.js, tiling-assistant@leleat-on-github/src/extension/utility.js
I tested it with Gnome 46 alpha using Fedora RawHide and it works fine just by updating the metadata file.
=> Add support for Gnome 46

scripts/aur-build/.SRCINFO, scripts/aur-build/PKGBUILD, tiling-assistant@leleat-on-github/metadata.json, translations/cs.po, translations/de_CH.po, translations/de_DE.po, translations/es.po, translations/hu.po, translations/it_IT.po, translations/ja.po, translations/main.pot, translations/nl.po, translations/pt_BR.po, translations/uk.po, translations/zh_TW.po
A new GNOME release is coming up... so let's make a new release of T-A that supports it (on EGO).
=> Release 46

CHANGELOG.md
Forgot to update the changelog, whoops...
=> Changelog: Add changes for version 46

tiling-assistant@leleat-on-github/src/extension/moveHandler.js
Fixes https://github.com/Leleat/Tiling-Assistant/issues/327.
I'm not quite sure why this kind of glitch starts from GNOME 46, but it makes sense to not resizing when the grab has been ended (aka, just a click), and I don't find anything wrong with this (even by dragging maximized window with mouse very quickly).
Tested with GNOME 46. (And feel free to close if this PR is fundamentally wrong.)
=> moveHandler: replace hack that no longer works in GNOME 46

CHANGELOG.md, scripts/aur-build/.SRCINFO, scripts/aur-build/PKGBUILD, tiling-assistant@leleat-on-github/metadata.json, translations/cs.po, translations/de_CH.po, translations/de_DE.po, translations/es.po, translations/hu.po, translations/it_IT.po, translations/ja.po, translations/main.pot, translations/nl.po, translations/pt_BR.po, translations/uk.po, translations/zh_TW.po
Fedora/Ubuntu will have a new release soon. So let's make a (small) release before then...
=> Release: Bump version to 47

tiling-assistant@leleat-on-github/src/extension/layoutsManager.js, translations/de_DE.po, translations/main.pot
The PanelButton Preferences text is not translated.
Some translation updates
=> Preferences PanelButton not translated

tiling-assistant@leleat-on-github/src/prefs/shortcutListener.js, tiling-assistant@leleat-on-github/src/ui/shortcutListener.ui
Not all occurences of "Disabled" are translated in prefs dialog
=> Disabled in Prefs not translated

tiling-assistant@leleat-on-github/src/extension/moveHandler.js, tiling-assistant@leleat-on-github/src/extension/tilingWindowManager.js
This prevents the extension from crashing the desktop when trying to access an unmanaging window. I don't know if this fixes the related issue since I don't know the root cause of the issue. But this certainly prevents _a_ crash.
Related: https://github.com/Leleat/Tiling-Assistant/issues/329
=> moveHandler: Assert window exists before operating on it

tiling-assistant@leleat-on-github/metadata.json, tiling-assistant@leleat-on-github/src/extension/focusHint.js
I did some manual testing and haven't found any issues. It seems like there isn't much to do for the port.
=> feat: port to GNOME 48
